# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 703aa6201de558c01bb3f8809f864142371e3b61a6e046cb841a5152eec404c4c1ce408cf87b185766c063023f46cf3d4253c50ab267bef682dcaf5327ef9908

test:
  secret_key_base: c7b6bba9a0886eaa4f97ac098bf35343552e3b087f873c6cadfbdab03cd45f48ceae9ccafeadc3d37e78afb51bac93a0cfe110856b15c63b775c3c28cf896692

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
